[app]
mode="prod"

[api]
port=8000
host="localhost"
schema="http://"

[db]
pool_max=100
host="localhost"
database="postgres"
user="postgres"
password="1234"
port=5432

[log]
level="debug"

[jwt]
access_token_expiry_hour=1
refresh_token_expiry_hour=240
access_token_secret="${ACCESS_TOKEN_SECRET}"
refresh_token_secret="${REFRESH_TOKEN_SECRET}"

[oauth2]
state_string="${STATE_STRING}"
[oauth2.google]
client_id="809180687156-dtbcgi3a9982gar8umj3sao982b28nf9.apps.googleusercontent.com"
client_secret="${GOOGLE_CLIENT_SECRET}"
